exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/
  data_pages:
    output: true
    permalink: /:path/data/

# Site title and description
title: "analytics.bmj.gov | BMJ's web traffic."
description: "Official data on web traffic to selected BMJ websites. Published by the BMJ Tech."

# Site's own URL
url: https://analytics.bmj.com

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: https://analytics.usa.gov/data/live

# GitHub information
org_name: BMJ-Ltd
repo_name: BMJ_Analytics_HackDay

# twitter information
twitter: usgsa

sass:
  sass_dir: sass
  style: nested
